from enum import StrEnum


class Benchmark(StrEnum):
    BBH = "bbh"
    GPQA = "gpqa"
    MMLU_PRO = "mmlu-pro"
    MMLU = "mmlu"

    @property
    def pretty_name(self) -> str:
        return {
            self.BBH: "BBH",
            self.GPQA: "GPQA (Main)",
            self.MMLU_PRO: "MMLU-Pro",
            self.MMLU: "MMLU",
        }[self]

    @property
    def subsets(self) -> list[str]:
        return {
            self.MMLU: [
                "mmlu_abstract_algebra",
                "mmlu_anatomy",
                "mmlu_astronomy",
                "mmlu_business_ethics",
                "mmlu_clinical_knowledge",
                "mmlu_college_biology",
                "mmlu_college_chemistry",
                "mmlu_college_computer_science",
                "mmlu_college_mathematics",
                "mmlu_college_medicine",
                "mmlu_college_physics",
                "mmlu_computer_security",
                "mmlu_conceptual_physics",
                "mmlu_econometrics",
                "mmlu_electrical_engineering",
                "mmlu_elementary_mathematics",
                "mmlu_formal_logic",
                "mmlu_global_facts",
                "mmlu_high_school_biology",
                "mmlu_high_school_chemistry",
                "mmlu_high_school_computer_science",
                "mmlu_high_school_european_history",
                "mmlu_high_school_geography",
                "mmlu_high_school_government_and_politics",
                "mmlu_high_school_macroeconomics",
                "mmlu_high_school_mathematics",
                "mmlu_high_school_microeconomics",
                "mmlu_high_school_physics",
                "mmlu_high_school_psychology",
                "mmlu_high_school_statistics",
                "mmlu_high_school_us_history",
                "mmlu_high_school_world_history",
                "mmlu_human_aging",
                "mmlu_human_sexuality",
                "mmlu_international_law",
                "mmlu_jurisprudence",
                "mmlu_logical_fallacies",
                "mmlu_machine_learning",
                "mmlu_management",
                "mmlu_marketing",
                "mmlu_medical_genetics",
                "mmlu_miscellaneous",
                "mmlu_moral_disputes",
                "mmlu_moral_scenarios",
                "mmlu_nutrition",
                "mmlu_philosophy",
                "mmlu_prehistory",
                "mmlu_professional_accounting",
            ],
            "bbh": [
                "bbh_boolean_expressions",
                "bbh_causal_judgement",
                "bbh_date_understanding",
                "bbh_disambiguation_qa",
                "bbh_formal_fallacies",
                "bbh_geometric_shapes",
                "bbh_hyperbaton",
                "bbh_logical_deduction_five_objects",
                "bbh_logical_deduction_seven_objects",
                "bbh_logical_deduction_three_objects",
                "bbh_movie_recommendation",
                "bbh_navigate",
                "bbh_object_counting",
                "bbh_penguins_in_a_table",
                "bbh_reasoning_about_colored_objects",
                "bbh_ruin_names",
                "bbh_salient_translation_error_detection",
                "bbh_snarks",
                "bbh_sports_understanding",
                "bbh_temporal_sequences",
                "bbh_tracking_shuffled_objects_five_objects",
                "bbh_tracking_shuffled_objects_seven_objects",
                "bbh_tracking_shuffled_objects_three_objects",
                "bbh_web_of_lies",
            ],
            "mmlu-pro": [
                "mmlu-pro_philosophy",
                "mmlu-pro_law",
                "mmlu-pro_engineering",
                "mmlu-pro_chemistry",
                "mmlu-pro_business",
                "mmlu-pro_psychology",
                "mmlu-pro_health",
                "mmlu-pro_biology",
                "mmlu-pro_history",
                "mmlu-pro_other",
                "mmlu-pro_economics",
                "mmlu-pro_physics",
                "mmlu-pro_computer science",
                "mmlu-pro_math",
            ],
            "gpqa": ["gpqa_main"],
        }[self]
